// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shgpttigszhzioeqyrbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoZ3B0dGlnc3poemlvZXF5cmJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwOTE2ODUsImV4cCI6MjA3MTY2NzY4NX0.Li03Hz6-irR7IvadhsPp8qPj1xkz02h0WXp1T2hHhD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});